dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-10.0.0
    packages:
      - clang-10.0.0

script:
  - CXX=/usr/bin/clang++-10.0.0 CC=/usr/bin/clang-10.0.0 cmake .
  - cmake --build .