name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Install Valgrind
      run: sudo apt-get install valgrind

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./test/calculator_test

    - name: Dir check
      working-directory: ${{runner.workspace}}/TP_CPP_M1
      run: ls
      
    - name: Valgrind Memcheck
      working-directory: ${{runner.workspace}}/build
      run: valgrind ./src/calculator_run < ${{runner.workspace}}/TP_CPP_M1/testMemleaks.txt
